export const FETCH_TODO_START = 'FETCH_TODO_START'
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
export const FETCH_TODO_FAIL = 'FETCH_TODO_FAIL'

export const ADD_TODO_START = 'ADD_TODO_START'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL'

export const EDIT_TODO_START = 'EDIT_TODO_START'
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS'
export const EDIT_TODO_FAIL = 'EDIT_TODO_FAIL'

export const DEL_TODO_START = 'DEL_TODO_START'
export const DEL_TODO_SUCCESS = 'DEL_TODO_SUCCESS'
export const DEL_TODO_FAIL = 'DEL_TODO_FAIL'


export const SELECT_TODO = 'SELECT_TODO'

export const CLEAR_ERROR = 'CLEAR_ERROR'
